### ISSUE TITLE
<FEATURE> Favorite/star/heart

### ISSUE THREAD

**Issue by jake5253** [chlegou/bitlist#3]
What about the possibility to "favorite" each website individually and only show "my favorites" so I don't have to trudge through a large list of websites that I may or may not have an account with/do or don't care to use.
Otherwise, this is freaking awesomeness!!!
Thanks for your consideration

**Comment by chlegou** [comment]
This Feature is available in BitList long time ago. How to:  
1. Click the star in the faucet.
2. go to top menu and open "Faucets Filter".
3. select: Faucets Filter -> Favourite, then click apply.

To remove (unstar) a faucet from favourite list, just click the star again.

Thanks for your interest in BitList.

**Comment by Sifat1212** [comment]
644568
